# -*- coding: utf-8 -*-
"""OpusClip_v2.1_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lx03bCLqZ8-rmHL9BM-JuwC-wogRmvg4

# 🎬 OpusClip Pipeline v2.1 — Arabic & English
> **Tajawal ExtraBold** (Arabic) · **Montserrat ExtraBold** (English) · BROLL blur · Smart Director · LLM selection

### What's new in v2.1
- ✅ `clean_for_subtitle()` — NFC normalisation + Unicode blacklist → no more Tofu boxes
- ✅ `fill_missing_words()` — recovers words Whisper drops (e.g. 'ألا' in 'ألا وهو؟')
- ✅ **Tajawal ExtraBold** for Arabic, **Montserrat ExtraBold** for English — per-line auto-detect
- ✅ Two-stage FFmpeg seek — **3–10× faster** clip extraction for long videos
- ✅ Face detection every 3rd frame — **3× faster** face scan
- ✅ Fade in/out (0.4 s) + audio loudness normalisation (EBU R128)
- ✅ Thumbnail JPEG saved alongside each clip

**Runtime:** `Runtime → Change runtime type → T4 GPU`

**Free APIs (Cell 2):** [Groq](https://console.groq.com) · [Gemini](https://aistudio.google.com/apikey) · opencode.ai

Run **Cells 1 → 8 in order**. Cells 3–8 cache results — safe to re-run.
"""

# ═══════════════════════════════════════════════════════════════
# 📦  CELL 1 — ENVIRONMENT SETUP  (v2.1)
# ═══════════════════════════════════════════════════════════════

import subprocess
import os
import shutil
import urllib.request
import zipfile


def _sh(cmd, label=""):
    print(f"  ➜  {label or cmd[:70]}")
    r = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if r.returncode != 0 and r.stderr.strip():
        print(f"     ⚠  {r.stderr.strip()[:200]}")
    return r

print("📦  [1/5] Python packages …")
_sh("pip install -q faster-whisper 'openai>=1.0' opencv-python yt-dlp dlib",
    "faster-whisper · openai · opencv · yt-dlp · dlib")

print("🔤  [2/5] System fonts (base) …")
_sh("apt-get install -y -q fonts-noto-core fonts-noto-extra "
    "fonts-noto-color-emoji fonts-dejavu-core",
    "Noto · DejaVu · Emoji")

print("🔤  [3/5] Professional subtitle fonts …")
_FONT_DIR = "/usr/share/fonts/truetype/custom"
os.makedirs(_FONT_DIR, exist_ok=True)

_DOWNLOADS = [
    # ── Tajawal — Best Arabic + Latin font for video subtitles ──────
    # Clean, modern, excellent Arabic shaping, supports full Arabic script
    ("Tajawal-ExtraBold.ttf",
     "https://github.com/google/fonts/raw/main/ofl/tajawal/Tajawal-ExtraBold.ttf"),
    ("Tajawal-Bold.ttf",
     "https://github.com/google/fonts/raw/main/ofl/tajawal/Tajawal-Bold.ttf"),
    # ── Montserrat ExtraBold — Premium English subtitle font ─────────
    # Geometric, bold, perfect contrast on any background
    ("Montserrat-ExtraBold.ttf",
     "https://github.com/google/fonts/raw/main"
     "/ofl/montserrat/static/Montserrat-ExtraBold.ttf"),
    ("Montserrat-Bold.ttf",
     "https://github.com/google/fonts/raw/main"
     "/ofl/montserrat/static/Montserrat-Bold.ttf"),
]

for _fname, _url in _DOWNLOADS:
    _fp = os.path.join(_FONT_DIR, _fname)
    if not os.path.exists(_fp):
        try:
            urllib.request.urlretrieve(_url, _fp)
            print(f"     ✓  {_fname}")
        except Exception as _e:
            print(f"     ⚠  {_fname} failed: {_e}")
    else:
        print(f"     ✓  {_fname} (cached)")

_sh("fc-cache -fv > /dev/null 2>&1", "fc-cache rebuild")

# ── Detect which fonts fontconfig can actually find ───────────
def _fc_has(family):
    r = subprocess.run(["fc-list", f":family={family}"],
                       capture_output=True, text=True)
    return bool(r.stdout.strip())

print("🔤  [3/5] Arabic subtitle font …")

# Download Amiri directly (works on Colab / Docker / Ubuntu)
AMIRI_URL = "https://github.com/aliftype/amiri/releases/latest/download/Amiri-1.003.zip"
AMIRI_ZIP = "/tmp/amiri.zip"
AMIRI_DIR = "/tmp/amiri"

try:
    if not os.path.exists(os.path.join(_FONT_DIR, "Amiri-Regular.ttf")):
        urllib.request.urlretrieve(AMIRI_URL, AMIRI_ZIP)

        subprocess.run(
            f"unzip -oq {AMIRI_ZIP} -d {AMIRI_DIR}",
            shell=True,
            check=True
        )

        # Copy every Amiri TTF recursively (the zip contains a subfolder)
        copied = 0

        for root, _, files in os.walk(AMIRI_DIR):
            for f in files:
                if f.lower().endswith(".ttf"):
                    src = os.path.join(root, f)
                    dst = os.path.join(_FONT_DIR, f)
                    shutil.copy2(src, dst)
                    copied += 1

        print(f"     ✓ Copied {copied} Amiri font files")

except Exception as e:
    print("     ⚠ Amiri download failed:", e)

_sh("fc-cache -fv > /dev/null 2>&1", "fc-cache")

print(
    "     fc-match:",
    subprocess.run(
        ["fc-match", "Amiri"],
        capture_output=True,
        text=True
    ).stdout.strip()
)

SUBTITLE_FONT_AR = next(
    (f for f in ["Amiri", "Tajawal", "Noto Sans Arabic", "Noto Sans"]
     if _fc_has(f)),
    "Noto Sans"
)

SUBTITLE_FONT_EN = next(
    (f for f in ["Montserrat", "Noto Sans"]
     if _fc_has(f)),
    "Noto Sans"
)

print(f"\n     Arabic font : {SUBTITLE_FONT_AR}")
print(f"     English font: {SUBTITLE_FONT_EN}")
print("🤖  [4/5] dlib model …")
DLIB_DAT = "shape_predictor_68_face_landmarks.dat"
if not os.path.exists(DLIB_DAT):
    r = _sh(f"wget -q https://github.com/italojs/facial-landmarks-recognition"
            f"/raw/master/{DLIB_DAT}", "dlib model")
    if not os.path.exists(DLIB_DAT):
        _sh(f"wget -q 'http://dlib.net/files/{DLIB_DAT}.bz2' -O {DLIB_DAT}.bz2")
        _sh(f"bzip2 -d {DLIB_DAT}.bz2")
else:
    print(f"     ✓  {DLIB_DAT} (cached)")

print("✅  [5/5] Verifying …")
_ok = True
for _lib in ["dlib","cv2","faster_whisper","openai"]:
    try: __import__(_lib); print(f"     ✓  {_lib}")
    except ImportError: print(f"     ✗  {_lib} FAILED"); _ok = False

print(f"\n{'🎉' if _ok else '❌'}  "
      f"{'Ready — proceed to Cell 2.' if _ok else 'Fix errors above.'}")

import subprocess

for font in ["Amiri", "Tajawal", "Montserrat", "Noto Sans"]:
    print("=" * 30)
    print(font)
    print(
        subprocess.run(
            ["fc-match", font],
            capture_output=True,
            text=True
        ).stdout
    )

import os

for root, dirs, files in os.walk("/tmp/amiri"):
    print(root)
    for f in files:
        print("   ", f)

# ═══════════════════════════════════════════════════════════════
# ⚙️  CELL 2 — CONFIGURATION
# ═══════════════════════════════════════════════════════════════

# ── LLM API options ────────────────────────────────────────────
# Groq FREE:   base_url = "https://api.groq.com/openai/v1"
#              model    = "llama-3.3-70b-versatile"
#              key from  console.groq.com
#
# Gemini FREE: base_url = "https://generativelanguage.googleapis.com/v1beta/openai/"
#              model    = "gemini-2.0-flash"
#              key from  aistudio.google.com/apikey
#
# opencode.ai: base_url = "https://opencode.ai/zen/v1"
#              model    = "deepseek-v4-flash-free"
# ───────────────────────────────────────────────────────────────

CONFIG = {
    "api_key"           : os.environ.get("OPUSCLIP_API_KEY", ""),           # ← set via env var
    "api_base"          : "https://opencode.ai/zen/v1",
    "model"             : "deepseek-v4-flash-free",

    "whisper_model"     : "large-v3",
    "whisper_language"  : None,   # None=auto, "ar"=Arabic, "en"=English

    "output_dir"        : "opusclip_output",
    "min_clips"         : 5,
    "max_clips"         : 12,
    "min_virality"      : 65,
    "min_duration"      : 40,
    "max_duration"      : 120,

    "target_height"     : 1920,
    "crf"               : 20,

    "speaking_mar"      : 0.025,
    "min_face_area"     : 0.003,
    "state_debounce_s"  : 0.6,
}

import os
os.makedirs(CONFIG["output_dir"], exist_ok=True)
os.makedirs(os.path.join(CONFIG["output_dir"], "work"),  exist_ok=True)
os.makedirs(os.path.join(CONFIG["output_dir"], "clips"), exist_ok=True)

print(f"✅  Config ready")
print(f"    API    : {CONFIG['api_base']}")
print(f"    Model  : {CONFIG['model']}")
print(f"    Whisper: {CONFIG['whisper_model']}")
# print(f"    Font   : {SUBTITLE_FONT}")
print(f"    Output : {CONFIG['output_dir']}/")
print(f"              ├── work/   (temp files)")
print(f"              ├── clips/  (final videos)")
print(f"              └── *.json  (cache)")

# ═══════════════════════════════════════════════════════════════
# 📁  CELL 3 — VIDEO INPUT
# ═══════════════════════════════════════════════════════════════

import subprocess, os, cv2

# ── Pick ONE mode ───────────────────────────────────────────────
INPUT_MODE  = "youtube"   # "upload"  |  "youtube"
YOUTUBE_URL = "https://youtu.be/OwDU3GH9cGI?si=MeHrfxVtdIUK5u9c"         # paste URL here if INPUT_MODE = "youtube"
# ───────────────────────────────────────────────────────────────

if INPUT_MODE == "upload":
    from google.colab import files as _cf
    print("📂  Select your video file …")
    uploaded   = _cf.upload()
    VIDEO_PATH = list(uploaded.keys())[0]
elif INPUT_MODE == "youtube":
    assert YOUTUBE_URL, "Set YOUTUBE_URL above!"
    VIDEO_PATH = os.path.join(CONFIG["output_dir"], "source_video.mp4")
    if not os.path.exists(VIDEO_PATH):
        print(f"⬇️   Downloading: {YOUTUBE_URL}")
        r = subprocess.run([
            "yt-dlp",
            "--format", "bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[height<=1080]",
            "--merge-output-format", "mp4", "--no-playlist",
            "--extractor-retries", "5",
            "--sleep-interval", "1", "--max-sleep-interval", "4",
            "--output", VIDEO_PATH, YOUTUBE_URL,
        ], capture_output=True, text=True)
        if r.returncode != 0:
            raise RuntimeError(f"Download failed:\n{r.stderr[-600:]}")
    else:
        print(f"✓  Cached: {VIDEO_PATH}")
else:
    raise ValueError("INPUT_MODE must be 'upload' or 'youtube'")

_cap      = cv2.VideoCapture(VIDEO_PATH)
VID_W     = int(_cap.get(cv2.CAP_PROP_FRAME_WIDTH))
VID_H     = int(_cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
VID_FPS   = float(_cap.get(cv2.CAP_PROP_FPS)) or 30.0
VID_NFRM  = int(_cap.get(cv2.CAP_PROP_FRAME_COUNT))
VID_DUR   = VID_NFRM / VID_FPS
_cap.release()

TARGET_H   = CONFIG["target_height"]
TARGET_W   = int(TARGET_H * 9 / 16)
if TARGET_W % 2: TARGET_W += 1

SRC_CROP_W = int(VID_H * 9 / 16)
if SRC_CROP_W % 2: SRC_CROP_W += 1

print(f"\n✅  {os.path.basename(VIDEO_PATH)}")
print(f"    Source     : {VID_W}×{VID_H}  {VID_FPS:.1f} fps  {VID_DUR/60:.1f} min")
print(f"    Crop window: {SRC_CROP_W}×{VID_H}  → output: {TARGET_W}×{TARGET_H}")

# ═══════════════════════════════════════════════════════════════
# 🎙️  CELL 4 — TRANSCRIPTION
# ═══════════════════════════════════════════════════════════════

import json, os, subprocess, time

TRANSCRIPT_JSON = os.path.join(CONFIG["output_dir"], "transcript.json")
AUDIO_WAV       = os.path.join(CONFIG["output_dir"], "audio.wav")

if os.path.exists(TRANSCRIPT_JSON):
    print(f"✅  Cached → {TRANSCRIPT_JSON}")
    with open(TRANSCRIPT_JSON, "r", encoding="utf-8") as f:
        transcript_data = json.load(f)
else:
    print("🔊  Extracting audio …")
    subprocess.run([
        "ffmpeg", "-y", "-i", VIDEO_PATH,
        "-vn", "-ar", "16000", "-ac", "1",
        "-c:a", "pcm_s16le", AUDIO_WAV,
    ], check=True, capture_output=True)
    print(f"     ✓  {os.path.getsize(AUDIO_WAV)//1_000_000} MB")

    from faster_whisper import WhisperModel
    import torch, gc

    print(f"📝  Whisper {CONFIG['whisper_model']} …")
    t0    = time.time()
    model = WhisperModel(CONFIG["whisper_model"], device="cuda",
                         compute_type="float16")

    # initial_prompt improves Egyptian Arabic accuracy significantly
    _lang = CONFIG["whisper_language"]
    _prompt = None
    if _lang == "ar" or _lang is None:
        _prompt = (
            "هذا برنامج أو بودكاست بالعامية المصرية. "
            "يتحدث المتحدثون بشكل طبيعي ويستخدمون كلمات "
            "عامية مثل: مش، بقى، دلوقتي، كمان، بتاع، "
            "عشان، إزيك، عايز، بيقول، بيعمل، هيجي، أهو، يعني."
        )

    seg_iter, info = model.transcribe(
        AUDIO_WAV,
        word_timestamps=True,
        language=_lang,
        initial_prompt=_prompt,
        temperature=0.0,
        condition_on_previous_text=True,
        vad_filter=True,
        vad_parameters=dict(min_silence_duration_ms=400),
    )
    print(f"     Language : {info.language}  ({info.language_probability:.0%})")

    segments, all_words = [], []
    for seg in seg_iter:
        words = []
        for w in (seg.words or []):
            prob = getattr(w, "probability", 1.0)
            if prob < 0.55: continue
            wd = {"text": w.word.strip(), "start": round(w.start,3),
                  "end": round(w.end,3), "prob": round(prob,3)}
            words.append(wd); all_words.append(wd)
        if words:
            segments.append({"start": round(seg.start,3), "end": round(seg.end,3),
                              "text": seg.text.strip(), "words": words})

    transcript_data = {"language": info.language, "duration": round(VID_DUR,2),
                       "segments": segments, "words": all_words}
    with open(TRANSCRIPT_JSON, "w", encoding="utf-8") as f:
        json.dump(transcript_data, f, ensure_ascii=False, indent=2)

    del model; torch.cuda.empty_cache(); gc.collect()
    print(f"✅  {len(segments)} segments · {len(all_words)} words  "
          f"({time.time()-t0:.0f}s) → {TRANSCRIPT_JSON}")

for s in transcript_data["segments"][:3]:
    print(f"  [{s['start']:.1f}s–{s['end']:.1f}s]  {s['text'][:80]}")
print("  …")

# ═══════════════════════════════════════════════════════════════
# 🤖  CELL 5 — SMART CLIP SELECTION
# ═══════════════════════════════════════════════════════════════

import json, os, re, time
from openai import OpenAI

CLIPS_JSON = os.path.join(CONFIG["output_dir"], "selected_clips.json")

def snap_boundary(ts, segments, direction="start", window=4.0):
    best, best_d = float(ts), float("inf")
    for seg in segments:
        cand = seg["start"] if direction == "start" else seg["end"]
        d = abs(cand - float(ts))
        if d < best_d and d <= window:
            best, best_d = cand, d
    return round(best, 3)

def compress_transcript(segments, max_chars=28_000):
    """Sample evenly across the full video within char budget."""
    all_lines = [f"[{s['start']:.1f}s-{s['end']:.1f}s]: {s['text']}"
                 for s in segments]
    total = sum(len(l) for l in all_lines)
    if total <= max_chars:
        return "\n".join(all_lines)
    step = max(1, round(total / max_chars))
    out, budget = [], 0
    for i, (seg, line) in enumerate(zip(segments, all_lines)):
        if i % step != 0: continue
        if budget + len(line) + 1 > max_chars:
            out.append(f"[… {segments[-1]['end']:.0f}s total …]")
            break
        out.append(line); budget += len(line) + 1
    print(f"    Sampled {len(out)}/{len(segments)} segments "
          f"({budget:,}/{total:,} chars)")
    return "\n".join(out)

def extract_json_array(text):
    if not text or not text.strip(): return None
    cleaned = re.sub(r"^```(?:json)?\s*", "", text.strip(), flags=re.IGNORECASE)
    cleaned = re.sub(r"\s*```$", "", cleaned).strip()
    m = re.search(r'\[.*\]', cleaned, re.DOTALL)
    if m:
        try: return json.loads(m.group())
        except: pass
    try: return json.loads(cleaned)
    except: return None

lang_hint = transcript_data.get("language", "ar")

CLIP_SYSTEM = f"""You are a world-class viral content strategist for Arabic and English short-form video.

TASK: Analyze the full transcript and select the best segments for viral vertical clips.

HOW MANY CLIPS:
  You decide — between {CONFIG['min_clips']} and {CONFIG['max_clips']} clips, based on quality alone.
  Only include clips scoring ≥ {CONFIG['min_virality']}/100. Never pad with weak content.
  Clips MAY OVERLAP if the same content serves two different story angles.

DURATION: {CONFIG['min_duration']}–{CONFIG['max_duration']} seconds.
  Prefer 40–90 s. Including one extra sentence is always better than cutting a thought short.

SENTENCE BOUNDARY RULE — MOST IMPORTANT:
  start = timestamp where a COMPLETE sentence/thought BEGINS (never mid-sentence)
  end   = timestamp where the COMPLETE thought is FULLY RESOLVED, including punchline
  Only use timestamps that appear in the [start-end] markers in the transcript.

VIRALITY SCORE (sum of 5 × 0–20 = 0–100):
  hook    — Do the first 5 words demand attention? Would someone stop scrolling?
  trigger — Activates: shock / awe / outrage / fear / curiosity / FOMO / relatability?
  value   — Rare knowledge, secret revealed, counterintuitive truth?
  arc     — Clear setup → tension/twist → resolution within this single clip?
  share   — Would viewers immediately tag someone or repost after watching?

TITLE LANGUAGE: Match the video language ({lang_hint}).
  Arabic content → Arabic titles. English content → English titles.

RETURN: ONLY a valid JSON array — no text before or after, no markdown fences.
[
  {{
    "clip_number"     : 1,
    "title"           : "≤80 chars · 1–2 emojis · match video language",
    "start"           : 0.0,
    "end"             : 0.0,
    "virality_score"  : 0,
    "score_breakdown" : {{"hook":0,"trigger":0,"value":0,"arc":0,"share":0}},
    "hook_line"       : "Exact first sentence that hooks the viewer",
    "reason"          : "2–3 sentences: hook, trigger, why viewers will share"
  }}
]"""

if os.path.exists(CLIPS_JSON):
    print(f"✅  Cached → {CLIPS_JSON}")
    with open(CLIPS_JSON, "r", encoding="utf-8") as f:
        selected_clips = json.load(f)
else:
    tx_text = compress_transcript(transcript_data["segments"])
    print(f"📤  Sending {len(tx_text):,} chars to LLM …")

    client     = OpenAI(api_key=CONFIG["api_key"], base_url=CONFIG["api_base"])
    clips_raw  = None
    raw_json   = ""

    for attempt in range(3):
        try:
            resp = client.chat.completions.create(
                model       = CONFIG["model"],
                messages    = [
                    {"role": "system", "content": CLIP_SYSTEM},
                    {"role": "user",   "content": f"Transcript:\n\n{tx_text}"},
                ],
                temperature = 0.20,
            )
            raw_json  = resp.choices[0].message.content or ""
            finish    = resp.choices[0].finish_reason
            usage     = resp.usage
            print(f"\n🔍 finish={finish} | in={usage.prompt_tokens} "
                  f"out={usage.completion_tokens} tokens")
            print(f"🔍 raw[:300]: {repr(raw_json[:300])}\n")

            clips_raw = extract_json_array(raw_json)
            if clips_raw is not None:
                print(f"✅  Parsed {len(clips_raw)} clips"); break
            else:
                print(f"⚠️  Attempt {attempt+1}: no JSON — retrying …")
                time.sleep(2)
        except Exception as e:
            print(f"⚠️  Attempt {attempt+1} API error: {e}"); time.sleep(3)

    if clips_raw is None:
        raise RuntimeError(
            f"No valid JSON after 3 attempts.\n"
            f"Raw: {raw_json[:500]}\n\n"
            f"Try: reduce compress_transcript max_chars or switch API."
        )

    REQUIRED = {"clip_number","title","start","end","virality_score",
                "score_breakdown","hook_line","reason"}
    segs     = transcript_data["segments"]
    selected_clips = []
    for c in clips_raw:
        if not REQUIRED.issubset(c.keys()):
            print(f"  ⚠  Clip {c.get('clip_number','?')} missing fields"); continue
        if c["virality_score"] < CONFIG["min_virality"]:
            print(f"  ⚠  Score {c['virality_score']} < {CONFIG['min_virality']}"); continue
        c["start"]    = snap_boundary(c["start"], segs, "start")
        c["end"]      = snap_boundary(c["end"],   segs, "end")
        c["duration"] = round(c["end"] - c["start"], 1)
        if not (CONFIG["min_duration"] <= c["duration"] <= CONFIG["max_duration"]):
            print(f"  ⚠  Duration {c['duration']}s out of range"); continue
        selected_clips.append(c)

    if not selected_clips:
        raise RuntimeError("No valid clips. Lower min_virality or check transcript.")

    selected_clips.sort(key=lambda x: x["virality_score"], reverse=True)
    for i, c in enumerate(selected_clips, 1): c["clip_number"] = i

    with open(CLIPS_JSON, "w", encoding="utf-8") as f:
        json.dump(selected_clips, f, ensure_ascii=False, indent=2)

print(f"\n✅  {len(selected_clips)} clips:")
for c in selected_clips:
    print(f"  [{c['clip_number']:2d}]  ★{c['virality_score']}  "
          f"{c['start']:.1f}–{c['end']:.1f}s ({c['duration']:.0f}s)  "
          f"{c['title'][:52]}")

# ═══════════════════════════════════════════════════════════════
# 🎬  CELL 6 — SMART DIRECTOR + RENDERING  (v2.1)
#
#  Changes vs v2.0:
#  ✅ clean_for_subtitle() — NFC + Unicode blacklist → no more boxes
#  ✅ fill_missing_words() — recovers "ألا" and other short words Whisper drops
#  ✅ build_ass()          — Tajawal/Montserrat, pro shadow, per-line lang font
#  ✅ render_clip()        — 2-stage FFmpeg seek (3-10x faster for long videos)
#  ✅ render_clip()        — face detection every 3rd frame (3x scan speedup)
#  ✅ render_clip()        — optional fade-in/out + audio normalisation
#  ✅ render_clip()        — thumbnail JPEG saved alongside clip
# ═══════════════════════════════════════════════════════════════

import cv2, dlib, re, os, json, subprocess, time, shutil, unicodedata
import numpy as np

VIDEO_LANG = transcript_data.get("language", "ar")   # set in Cell 4

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Text cleaning
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Characters known to render as hollow boxes in libass / Cairo / Tajawal
_BAD_CHARS = re.compile(
    "["
    # Emoji ranges (full)
    u"\U0001F600-\U0001F64F\U0001F300-\U0001F5FF"
    u"\U0001F680-\U0001F6FF\U0001F700-\U0001F77F"
    u"\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF"
    u"\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F"
    u"\U00002702-\U000027B0\U000024C2-\U0001F251"
    u"\U0001F1E0-\U0001F1FF"
    # Control / non-printable / BOM / zero-width space
    u"\U00000000-\U0000001F"   # C0 controls
    u"\U0000007F-\U0000009F"   # DEL + C1 controls
    u"\U0000200B"              # zero-width space
    u"\U0000FEFF"              # BOM / ZWNBSP
    # Variation selectors and language tags (invisible but cause boxes)
    u"\U0000FE00-\U0000FE0F"
    u"\U000E0000-\U000E007F"
    "]+",
    flags=re.UNICODE,
)

def clean_for_subtitle(text: str) -> str:
    """
    Whitelist-based cleaning — character by character.
    Drops EVERYTHING that's not explicitly Arabic or Latin.
    No regex, no missing emoji ranges, no bugs.
    """
    if not text:
        return ""
    text = unicodedata.normalize("NFC", text)
    result = []
    for ch in text:
        cp = ord(ch)
        keep = (
            0x0020 <= cp <= 0x007E or   # ASCII printable (letters, digits, punct)
            0x00C0 <= cp <= 0x024F or   # Latin Extended A/B (é, ü, etc.)
            0x0600 <= cp <= 0x06FF or   # Arabic main block
            0x0750 <= cp <= 0x077F or   # Arabic Supplement
            0x08A0 <= cp <= 0x08FF or   # Arabic Extended-A
            0xFB50 <= cp <= 0xFDFF or   # Arabic Presentation Forms-A
            0xFE70 <= cp <= 0xFEFF or   # Arabic Presentation Forms-B
            cp == 0x0640 or             # Arabic Tatweel (kashida ـ)
            cp in (
                0x060C,  # Arabic comma ،
                0x061B,  # Arabic semicolon ؛
                0x061F,  # Arabic question mark ؟
                0x200C,  # ZWNJ (needed for correct Arabic rendering)
                0x200D,  # ZWJ  (needed for correct Arabic rendering)
                0x2019,  # Right single quote '
                0x201C,  # Left double quote "
                0x201D,  # Right double quote "
                0x2026,  # Ellipsis …
                0x2013,  # En dash –
                0x2014,  # Em dash —
            )
        )
        if keep:
            result.append(ch)
    # Collapse multiple spaces into one
    return " ".join("".join(result).split())


def is_arabic_text(text: str) -> bool:
    return len(re.findall(r"[\u0600-\u06FF]", text)) > len(text) * 0.3


def subtitle_font(line_text: str) -> str:
    """Pick the right font based on the dominant script in a line."""
    return SUBTITLE_FONT_AR if is_arabic_text(line_text) else SUBTITLE_FONT_EN


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Word timestamp repair
# (Whisper sometimes drops first word of very short segments)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def fill_missing_words(transcript_data: dict) -> list:
    """
    For each segment, if the word-level timestamps are missing words
    that appear in the segment text, reconstruct them by interpolating
    the available time before the first timestamped word.

    Example: segment text = "ألا وهو؟"  but words = [{"text":"وهو؟",...}]
    → reconstructs {"text":"ألا", "start": seg.start, "end": gap/1}
    """
    result = []
    for seg in transcript_data.get("segments", []):
        ts_words  = seg.get("words", [])
        txt_words = [w for w in seg["text"].strip().split() if w]

        # Enough coverage → use as-is
        if not txt_words or len(ts_words) >= len(txt_words) * 0.7:
            result.extend(ts_words)
            continue

        ts_texts = {w["text"].strip() for w in ts_words}
        missing  = [w for w in txt_words if w not in ts_texts]

        if not missing:
            result.extend(ts_words)
            continue

        # Time available before first known word
        first_known = ts_words[0]["start"] if ts_words else seg["end"]
        gap         = first_known - seg["start"]

        if gap >= 0.05 * len(missing):          # at least 50ms per word
            dt = gap / len(missing)
            # print(dt)
            # for i, mw in enumerate(missing):
            #     result.append({
            #         "text"  : mw,
            #         "start" : round(seg["start"] + i * dt, 3),
            #         "end"   : round(seg["start"] + (i + 1) * dt, 3),
            #         "prob"  : 0.60,              # estimated
            #     })

            # داخل loop الكلمات المعاد بناؤها
            for i, mw in enumerate(missing):
                clean_mw = clean_for_subtitle(mw)   # ← clean BEFORE adding
                if not clean_mw:
                    continue
                result.append({
                    "text"  : clean_mw,
                    "start" : round(seg["start"] + i * dt, 3),
                    "end"   : round(seg["start"] + (i + 1) * dt, 3),
                    "prob"  : 0.60,
                })

        result.extend(ts_words)

    return sorted(result, key=lambda w: w["start"])


# Apply repair once, reuse for all clips
all_words_fixed = fill_missing_words(transcript_data)
print(f"ℹ️   Words: {len(transcript_data['words'])} original → "
      f"{len(all_words_fixed)} after repair")


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# ASS subtitle builder  (professional look)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def sec2ass(sec, offset=0.0):
    t  = max(0.0, sec - offset)
    cs = int(round(t * 100))
    h  = cs // 360000
    m  = (cs % 360000) // 6000
    s  = (cs % 6000)   // 100
    c  = cs % 100
    return f"{h}:{m:02d}:{s:02d}.{c:02d}"


def build_ass(words, clip_start, clip_end, tw, th, title):
    """
    Professional karaoke subtitles — v2.2 fix:
    • Style-level Bold=-1  (libass picks heaviest bold variant correctly)
    • NO inline \\fn tags  (they caused boxes when family name not exact-matched)
    • Active word = yellow colour only, inactive = white
    • Per-line Ar/En style switch for correct font per script
    """
    fs      = max(26, int(th * 0.052))
    fs_hook = max(30, int(th * 0.058))
    outline = max(6,   int(th * 0.0045))
    shadow  = 3
    mv      = int(th * 0.07)
    mv_hook = int(th * 0.04)

    font_ar = SUBTITLE_FONT_AR   # e.g. "Tajawal"
    font_en = SUBTITLE_FONT_EN   # e.g. "Montserrat"

    header = (
        "[Script Info]\n"
        "ScriptType: v4.00+\n"
        f"PlayResX: {tw}\nPlayResY: {th}\n"
        "YCbCr Matrix: TV.601\n\n"

        "[V4+ Styles]\n"
        "Format: Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,"
        "OutlineColour,BackColour,Bold,Italic,Underline,StrikeOut,"
        "ScaleX,ScaleY,Spacing,Angle,BorderStyle,Outline,Shadow,"
        "Alignment,MarginL,MarginR,MarginV,Encoding\n"

        # Bold=-1 → libass picks the heaviest bold weight from the family
        # BackColour &H99000000 = semi-transparent dark drop shadow
        f"Style: Ar,{font_ar},{fs},"
        f"&H00FFFFFF,&H000000FF,&H00000000,&H99000000,"
        f"-1,0,0,0,100,100,0,0,1,{outline},{shadow},2,20,20,{mv},1\n"

        f"Style: En,{font_en},{fs},"
        f"&H00FFFFFF,&H000000FF,&H00000000,&H99000000,"
        f"-1,0,0,0,100,100,0,0,1,{outline},{shadow},2,20,20,{mv},1\n"

        # Hook title — golden colour, top-centre
        f"Style: Hook,{font_ar},{fs_hook},"
        f"&H001ADFFF,&H000000FF,&H00000000,&HAA000000,"
        f"-1,0,0,0,100,100,0,0,1,{outline},{shadow},8,20,20,{mv_hook},1\n\n"

        "[Events]\n"
        "Format: Layer,Start,End,Style,Name,MarginL,MarginR,MarginV,Effect,Text\n"
    )

    events = ""

    # Hook title — first 3 seconds
    clean_t = clean_for_subtitle(title)
    print(f"   🔍 Title raw : {repr(title[:60])}")
    print(f"   🔍 Title clean: {repr(clean_t[:60])}")
    if clean_t:
        events += (f"Dialogue: 0,{sec2ass(clip_start,clip_start)},"
                   f"{sec2ass(clip_start+3,clip_start)},Hook,,0,0,0,,{clean_t}\n")

    # Collect words for this clip
    clip_ws = []
    for w in words:
        mid = (w["start"] + w["end"]) / 2.0
        if clip_start <= mid <= clip_end:
            txt = clean_for_subtitle(w["text"].strip())
            if txt:
                clip_ws.append({"text": txt,
                                 "start": w["start"], "end": w["end"]})
    if not clip_ws:
        return header + events

    # Group into lines: max 3 words or gap > 0.45 s
    lines, cur = [], [clip_ws[0]]
    for i in range(1, len(clip_ws)):
        gap = clip_ws[i]["start"] - clip_ws[i-1]["end"]
        if len(cur) >= 3 or gap > 0.45:
            lines.append(cur); cur = []
        cur.append(clip_ws[i])
    if cur:
        lines.append(cur)

    # Karaoke entries
    for line in lines:
        n         = len(line)
        line_text = " ".join(lw["text"] for lw in line)
        style     = "Ar" if is_arabic_text(line_text) else "En"

        for i, word in enumerate(line):
            w_start = word["start"]
            w_end   = line[i+1]["start"] if i < n-1 else line[-1]["end"]

            parts = []
            for j, lw in enumerate(line):
                t = clean_for_subtitle(lw["text"])
                if j == i:
                    # Active word: yellow — no \fn, no \b (style handles bold)
                    parts.append(f"{{\\c&H0000FFFF&}}{t}{{\\c&HFFFFFF&}}")
                else:
                    # Inactive: plain white, font from style
                    parts.append(t)

            display = " ".join(parts)
            ts = sec2ass(w_start, clip_start)
            te = sec2ass(w_end,   clip_start)
            events += f"Dialogue: 0,{ts},{te},{style},,0,0,0,,{display}\n"

    return header + events


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# B-roll blurred background
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def make_broll_frame(frame_bgr, tgt_w, tgt_h):
    src_h, src_w = frame_bgr.shape[:2]
    # Blurred + darkened background
    bg = cv2.resize(frame_bgr, (tgt_w, tgt_h), interpolation=cv2.INTER_LINEAR)
    bg = cv2.GaussianBlur(bg, (71, 71), 0)
    bg = (bg.astype(np.float32) * 0.28).clip(0, 255).astype(np.uint8)
    # Clean letterboxed panel
    fg_w = tgt_w
    fg_h = int(fg_w * src_h / src_w)
    if fg_h > int(tgt_h * 0.95):
        fg_h = int(tgt_h * 0.95)
        fg_w = int(fg_h * src_w / src_h)
        if fg_w % 2: fg_w -= 1
    fg = cv2.resize(frame_bgr, (fg_w, fg_h), interpolation=cv2.INTER_LANCZOS4)
    bd = 5
    fg = cv2.copyMakeBorder(fg, bd, bd, bd, bd,
                             cv2.BORDER_CONSTANT, value=(245, 245, 245))
    fg_h, fg_w = fg.shape[:2]
    result = bg.copy()
    y0 = max(0, (tgt_h - fg_h) // 2)
    y1 = min(tgt_h, y0 + fg_h)
    x0 = max(0, (tgt_w - fg_w) // 2)
    x1 = min(tgt_w, x0 + fg_w)
    result[y0:y1, x0:x1] = fg[:y1-y0, :x1-x0]
    return result


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Smart Director
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

class SmartDirector:
    SOLO = 0; GROUP = 1; BROLL = 2

    def __init__(self, vid_w, vid_h, src_crop_w, fps,
                 speaking_mar=0.025, min_face_area=0.003, debounce_s=0.6):
        self.vw = vid_w; self.vh = vid_h; self.cw = src_crop_w
        self.fps = fps; self.MAR_THR = speaking_mar
        self.AREA_THR = min_face_area
        self.HOLD = max(1, int(fps * debounce_s))
        self.GRP_SPREAD = src_crop_w * 0.55
        self.smooth_x = vid_w // 2
        self.state = self.BROLL; self.hold_count = 0
        self.ALPHA_SOLO = 0.07; self.ALPHA_GROUP = 0.04
        self.ALPHA_BROLL = 0.012
        self.MAX_DX = max(1, int(src_crop_w * 0.04))

    def _crop_start(self):
        return max(0, min(self.smooth_x - self.cw // 2, self.vw - self.cw))

    def update(self, faces):
        valid  = [f for f in faces if f.get("area_ratio", 0) >= self.AREA_THR]
        active = [f for f in valid  if f.get("mar_norm",   0) >  self.MAR_THR]

        if not valid:               desired = self.BROLL
        elif not active:            desired = self.state
        elif len(active) == 1:      desired = self.SOLO
        else:
            xs = [f["x"] for f in active]
            desired = self.SOLO if (max(xs)-min(xs)) < self.GRP_SPREAD else self.GROUP

        if desired != self.state:
            self.hold_count += 1
            if self.hold_count >= self.HOLD:
                self.state = desired; self.hold_count = 0
        else:
            self.hold_count = max(0, self.hold_count - 2)

        if self.state == self.SOLO:
            src = active or valid
            tx  = (sum(f["x"] for f in src) // len(src)) if src else self.vw // 2
            alpha = self.ALPHA_SOLO
        elif self.state == self.GROUP:
            src = active or valid
            xs  = [f["x"] for f in src]
            tx  = ((min(xs) + max(xs)) // 2) if xs else self.vw // 2
            alpha = self.ALPHA_GROUP
        else:
            tx = self.vw // 2; alpha = self.ALPHA_BROLL

        raw_dx = int(alpha * (tx - self.smooth_x))
        self.smooth_x += max(-self.MAX_DX, min(self.MAX_DX, raw_dx))
        return self._crop_start()


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Face detection
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

_detector  = dlib.get_frontal_face_detector()
_predictor = dlib.shape_predictor(DLIB_DAT)

def detect_faces(frame_bgr, frame_area, scan_scale=1.0):
    gray = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2GRAY)
    dets, scores, _ = _detector.run(gray, 1, 0.0)
    faces = []
    for rect, score in zip(dets, scores):
        fw, fh = rect.width(), rect.height()
        ar = (fw * fh) / frame_area
        if ar < 0.002: continue
        shape = _predictor(gray, rect)
        mar   = abs(shape.part(51).y - shape.part(57).y) / max(fh, 1)
        faces.append({
            "x": int((rect.left() + fw/2) / scan_scale),
            "y": int((rect.top()  + fh/2) / scan_scale),
            "w": int(fw / scan_scale), "h": int(fh / scan_scale),
            "mar_norm": round(mar, 4), "area_ratio": round(ar, 5),
        })
    return faces


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Per-clip rendering pipeline  (v2.1)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Tunable options
FACE_DETECT_EVERY = 3    # detect faces every N frames (3 = 3x speedup)
ADD_FADE          = True  # fade-in 0.4s + fade-out 0.4s
NORMALISE_AUDIO   = True  # EBU R128 loudness normalisation
SAVE_THUMBNAIL    = True  # save best-face frame as JPEG


def render_clip(clip, words, video_path, out_dir,
                vid_w, vid_h, vid_fps, src_crop_w, tgt_w, tgt_h, crf=20):

    n        = clip["clip_number"]
    title    = clip["title"]
    c_start  = clip["start"]
    c_end    = clip["end"]
    duration = clip["duration"]

    work_dir  = os.path.join(out_dir, "work")
    clips_dir = os.path.join(out_dir, "clips")
    os.makedirs(work_dir,  exist_ok=True)
    os.makedirs(clips_dir, exist_ok=True)

    base        = f"clip_{n:02d}"
    raw_path    = os.path.join(work_dir,  f"{base}_raw.mp4")
    scan_path   = os.path.join(work_dir,  f"{base}_scan.mp4")
    silent_path = os.path.join(work_dir,  f"{base}_silent.mp4")
    audio_path  = os.path.join(work_dir,  f"{base}_audio.aac")
    ass_path    = os.path.join(work_dir,  f"{base}.ass")
    safe_ass    = f"/tmp/{base}.ass"
    thumb_path  = os.path.join(clips_dir, f"{base}_thumb.jpg")
    final_path  = os.path.join(clips_dir, f"{base}_FINAL.mp4")

    if os.path.exists(final_path):
        print(f"  ✓  Clip {n} already rendered — skip")
        return final_path

    print(f"\n{'─'*62}")
    print(f"🎬  Clip {n}/{len(selected_clips)}  ★{clip['virality_score']}")
    print(f"    {title[:60]}")
    print(f"    {c_start:.1f}s → {c_end:.1f}s  ({duration:.0f}s)")
    t0 = time.time()

    # ── Step 1: Two-stage seek  (PERFORMANCE KEY FIX) ─────────────
    # Stage A: input seek to keyframe ≤10s before clip  (fast, imprecise)
    # Stage B: output seek for remaining seconds        (slow but only ≤10s)
    print("    [1/4] Cutting raw clip …")
    PRE_SEEK  = max(0.0, c_start - 10.0)
    FINE_SEEK = c_start - PRE_SEEK          # 0–10 s to decode precisely

    r = subprocess.run([
        "ffmpeg", "-y",
        "-ss", f"{PRE_SEEK:.3f}",            # A: jump to keyframe (microseconds)
        "-i",  video_path,
        "-ss", f"{FINE_SEEK:.3f}",           # B: fine-tune from there (≤10s)
        "-t",  f"{duration + 0.5:.3f}",      # +0.5s safety buffer
        "-c:v", "libx264", "-preset", "ultrafast", "-crf", "22",
        "-c:a", "aac", "-b:a", "128k",
        raw_path,
    ], capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f"Raw clip failed:\n{r.stderr[-400:]}")

    # Extract audio
    audio_filter = "loudnorm=I=-16:TP=-1.5:LRA=11" if NORMALISE_AUDIO else "anull"
    subprocess.run([
        "ffmpeg", "-y", "-i", raw_path,
        "-vn", "-af", audio_filter,
        "-c:a", "aac", "-b:a", "128k", audio_path,
    ], check=True, capture_output=True)

    # ── Step 2: Face scan at 480p — every FACE_DETECT_EVERY frames ──
    print("    [2/4] Scanning faces …")
    SCAN_H     = min(480, vid_h)
    scan_scale = SCAN_H / vid_h
    SCAN_W     = int(vid_w * scan_scale)
    if SCAN_W % 2: SCAN_W += 1

    r = subprocess.run([
        "ffmpeg", "-y", "-i", raw_path,
        "-vf", f"scale={SCAN_W}:{SCAN_H}",
        "-c:v", "libx264", "-preset", "ultrafast", "-crf", "28",
        "-an", scan_path,
    ], capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f"Scan failed:\n{r.stderr[-400:]}")

    scan_cap     = cv2.VideoCapture(scan_path)
    scan_area    = SCAN_W * SCAN_H
    frames_faces = []
    last_faces   = []
    fi = 0
    while True:
        ok, frame = scan_cap.read()
        if not ok: break
        if fi % FACE_DETECT_EVERY == 0:       # ← detect only every 3rd frame
            last_faces = detect_faces(frame, scan_area, scan_scale)
        frames_faces.append(last_faces)        # rest inherit last result
        fi += 1
    scan_cap.release()
    os.remove(scan_path)
    n_frames = len(frames_faces)
    detected = sum(1 for ff in frames_faces if ff)
    print(f"         {n_frames} frames  |  faces in {detected} frames  "
          f"(sampled every {FACE_DETECT_EVERY})")

    # ── Step 3: Director decisions per frame ──────────────────────
    director = SmartDirector(
        vid_w, vid_h, src_crop_w, vid_fps,
        speaking_mar  = CONFIG["speaking_mar"],
        min_face_area = CONFIG["min_face_area"],
        debounce_s    = CONFIG["state_debounce_s"],
    )
    director.smooth_x = vid_w // 2
    frame_data = [(director.update(ff), director.state)
                  for ff in frames_faces]

    # ── Step 4: Render with smart crop ───────────────────────────
    print("    [3/4] Rendering smart crop …")
    ffpipe = subprocess.Popen([
        "ffmpeg", "-y",
        "-f", "rawvideo", "-vcodec", "rawvideo",
        "-pix_fmt", "bgr24", "-s", f"{tgt_w}x{tgt_h}",
        "-r", str(vid_fps), "-i", "pipe:0",
        "-vcodec", "libx264", "-preset", "fast",
        "-crf", str(crf), "-pix_fmt", "yuv420p",
        silent_path,
    ], stdin=subprocess.PIPE, stderr=subprocess.DEVNULL)

    raw_cap    = cv2.VideoCapture(raw_path)
    fi         = 0
    best_frame = None      # for thumbnail
    best_face_area = 0.0

    while True:
        ok, frame = raw_cap.read()
        if not ok: break

        cx, fstate = frame_data[fi] if fi < len(frame_data) else frame_data[-1]

        if fstate == SmartDirector.BROLL:
            resized = make_broll_frame(frame, tgt_w, tgt_h)
        else:
            cx      = max(0, min(cx, vid_w - src_crop_w))
            cropped = frame[:, cx : cx + src_crop_w]
            resized = cv2.resize(cropped, (tgt_w, tgt_h),
                                 interpolation=cv2.INTER_LINEAR)
            # Track best frame for thumbnail (largest face, mid-clip range)
            if SAVE_THUMBNAIL and frames_faces[fi] and \
               n_frames * 0.25 < fi < n_frames * 0.75:
                fa = max(f["area_ratio"] for f in frames_faces[fi])
                if fa > best_face_area:
                    best_face_area = fa
                    best_frame     = resized.copy()

        ffpipe.stdin.write(resized.tobytes())
        fi += 1

    raw_cap.release()
    ffpipe.stdin.close()
    ffpipe.wait()

    # Save thumbnail
    if SAVE_THUMBNAIL and best_frame is not None:
        cv2.imwrite(thumb_path, best_frame, [cv2.IMWRITE_JPEG_QUALITY, 92])

    # ── Step 5: Subtitles + merge ─────────────────────────────────
    print("    [4/4] Burning subtitles …")
    ass_content = build_ass(words, c_start, c_end, tgt_w, tgt_h, title)
    with open(ass_path, "w", encoding="utf-8") as f:
        f.write(ass_content)
    shutil.copy(ass_path, safe_ass)

    # Build video filter: subtitles + optional fade
    vf_parts = [f"subtitles={safe_ass}"]
    if ADD_FADE:
        fade_d = 0.4
        vf_parts += [
            f"fade=t=in:st=0:d={fade_d}",
            f"fade=t=out:st={max(0, duration-fade_d):.2f}:d={fade_d}",
        ]
    vf = ",".join(vf_parts)

    merge = subprocess.run([
        "ffmpeg", "-y",
        "-i", silent_path, "-i", audio_path,
        "-vf", vf,
        "-c:v", "libx264", "-preset", "fast", "-crf", str(crf),
        "-c:a", "aac", "-b:a", "128k",
        "-shortest", final_path,
    ], capture_output=True, text=True)

    if merge.returncode != 0:
        print(f"     ⚠  Subtitle burn failed → saving without subs")
        subprocess.run([
            "ffmpeg", "-y", "-i", silent_path, "-i", audio_path,
            "-c:v", "copy", "-c:a", "copy", "-shortest", final_path,
        ], check=True, capture_output=True)

    for p in [raw_path, silent_path, audio_path, safe_ass]:
        try: os.remove(p)
        except: pass

    mb = os.path.getsize(final_path) / 1_000_000
    print(f"    ✅  {mb:.1f} MB — {time.time()-t0:.0f}s → "
          f"{os.path.basename(final_path)}"
          + (f"  + thumb" if SAVE_THUMBNAIL and best_frame is not None else ""))
    return final_path


# ── Process all clips ──────────────────────────────────────────
rendered = {}
for clip in selected_clips:
    try:
        path = render_clip(
            clip,
            all_words_fixed,         # ← repaired word list (recovers dropped words)
            VIDEO_PATH, CONFIG["output_dir"],
            VID_W, VID_H, VID_FPS,
            SRC_CROP_W, TARGET_W, TARGET_H,
            crf=CONFIG["crf"],
        )
        rendered[clip["clip_number"]] = path
    except Exception as exc:
        import traceback
        print(f"\n❌  Clip {clip['clip_number']} failed: {exc}")
        traceback.print_exc()

print(f"\n\n🎉  {len(rendered)}/{len(selected_clips)} clips rendered.")

# ═══════════════════════════════════════════════════════════════
# 📱  CELL 7 — PLATFORM METADATA
# ═══════════════════════════════════════════════════════════════

import json, os, re
from openai import OpenAI

META_JSON  = os.path.join(CONFIG["output_dir"], "metadata.json")
client     = OpenAI(api_key=CONFIG["api_key"], base_url=CONFIG["api_base"])
VIDEO_LANG = transcript_data.get("language", "ar")

META_SYS = f"""You are a senior social media strategist for Arabic and English content.
Video language: {VIDEO_LANG}. Match this language in all copy.
Return ONLY valid JSON — no text before or after, no markdown fences:
{{
  "youtube": {{
    "title"          : "SEO title ≤100 chars — primary keyword first",
    "description"    : "400–550 char: hook → context → insight → CTA. 3–4 inline hashtags.",
    "tags"           : ["15–20 tags: broad + niche + language-appropriate"],
    "thumbnail_text" : "5–7 bold words for thumbnail overlay"
  }},
  "tiktok": {{
    "caption"  : "≤150 chars: hook + CTA. 5–7 inline hashtags.",
    "hashtags" : ["8–10 high-volume TikTok hashtags"]
  }},
  "instagram": {{
    "caption"  : "120–200 chars: hook first, end with engaging question.",
    "hashtags" : ["25–30 hashtags — niche + broad + language-appropriate"]
  }},
  "twitter": {{
    "tweet"       : "≤230 chars: hook → insight → CTA. Max 3 hashtags.",
    "thread_hook" : "≤230 chars: opening tweet if this became a thread"
  }}
}}"""

def gen_meta(clip):
    resp = client.chat.completions.create(
        model    = CONFIG["model"],
        messages = [
            {"role": "system", "content": META_SYS},
            {"role": "user",   "content":
                f"Title: {clip['title']}\n"
                f"Duration: {clip['duration']}s\n"
                f"Hook: {clip['hook_line']}\n"
                f"Why viral: {clip['reason']}\n"
                f"Score: {clip['virality_score']}/100"},
        ],
        temperature = 0.40,
    )
    raw = resp.choices[0].message.content.strip()
    raw = re.sub(r"^```(?:json)?\s*", "", raw, flags=re.IGNORECASE)
    raw = re.sub(r"\s*```$", "", raw)
    return json.loads(raw)

if os.path.exists(META_JSON):
    print(f"✅  Cached → {META_JSON}")
    with open(META_JSON, "r", encoding="utf-8") as f:
        all_meta = json.load(f)
else:
    all_meta = {}
    for clip in selected_clips:
        n = str(clip["clip_number"])
        print(f"📱  Clip {n}: {clip['title'][:45]} …")
        try:    all_meta[n] = gen_meta(clip)
        except Exception as e:
            print(f"     ⚠  {e}"); all_meta[n] = {}
    with open(META_JSON, "w", encoding="utf-8") as f:
        json.dump(all_meta, f, ensure_ascii=False, indent=2)

for clip in selected_clips:
    n    = str(clip["clip_number"])
    meta = all_meta.get(n, {})
    print(f"\n{'═'*64}")
    print(f"  CLIP {n}  ★{clip['virality_score']}  |  {clip['title']}")
    print(f"{'═'*64}")
    yt = meta.get("youtube", {})
    if yt:
        print(f"\n  ▶  YOUTUBE")
        print(f"  Title : {yt.get('title','')}")
        d = yt.get("description","")
        print(f"  Desc  : {d[:160]}{'…' if len(d)>160 else ''}")
        print(f"  Tags  : {', '.join(yt.get('tags',[])[:8])}")
        print(f"  Thumb : {yt.get('thumbnail_text','')}")
    tt = meta.get("tiktok", {})
    if tt:
        print(f"\n  🎵 TIKTOK")
        print(f"  {tt.get('caption','')}")
        print(f"  {' '.join(tt.get('hashtags',[])[:7])}")
    ig = meta.get("instagram", {})
    if ig:
        print(f"\n  📸 INSTAGRAM")
        print(f"  {ig.get('caption','')}")
        print(f"  {' '.join(ig.get('hashtags',[])[:10])}")
    tw = meta.get("twitter", {})
    if tw:
        print(f"\n  🐦 TWITTER / X")
        print(f"  {tw.get('tweet','')}")

# ═══════════════════════════════════════════════════════════════
# 📥  CELL 8 — SUMMARY & DOWNLOAD
# ═══════════════════════════════════════════════════════════════

import os
from google.colab import files as _cf

print(f"\n{'═'*64}")
print("  🎉  PIPELINE COMPLETE")
print(f"{'═'*64}")
print(f"  Source   : {os.path.basename(VIDEO_PATH)}")
print(f"  Language : {transcript_data.get('language','?')}")
# print(f"  Font     : {SUBTITLE_FONT}")
print(f"  Duration : {transcript_data.get('duration',0)/60:.1f} min")
print()

total_mb = 0
clips_dir = os.path.join(CONFIG["output_dir"], "clips")
for clip in selected_clips:
    n    = clip["clip_number"]
    path = rendered.get(n)
    if path and os.path.exists(path):
        mb        = os.path.getsize(path) / 1_000_000
        total_mb += mb
        print(f"  [{n:2d}]  ★{clip['virality_score']}  "
              f"{clip['duration']:.0f}s  {mb:.1f}MB  "
              f"{os.path.basename(path)}")
    else:
        print(f"  [{n:2d}]  ✗  NOT RENDERED")

print(f"\n  Total   : {total_mb:.1f} MB")
print(f"  Folder  : {clips_dir}/")
print(f"\n  Cache:")
print(f"    {CONFIG['output_dir']}/transcript.json")
print(f"    {CONFIG['output_dir']}/selected_clips.json")
print(f"    {CONFIG['output_dir']}/metadata.json")
print("""
─────────────────────────────────────────
  DOWNLOAD
─────────────────────────────────────────
  # One clip:
  from google.colab import files
  files.download(rendered[1])

  # All clips:
  for p in rendered.values():
      files.download(p)
─────────────────────────────────────────
""")
# Uncomment to auto-download:
for path in rendered.values(): _cf.download(path)

